### PR TITLE
feat(orders): more match detail

### PR DESCRIPTION
**Pull request by LarsSelbekk**
Show end date and blid for match-receive orders.

### CODE REVIEW

**Comment by LarsSelbekk** [comment]
[Match-transfer-endringer](https://trello.com/c/ldr8Dw6e/1117-match-transfer-endringer)

**Comment by LarsSelbekk** [comment]
Show deadline and blid for `match-receive`
image

No change to `match-deliver`
image

**Comment by LarsSelbekk** [comment]
Approvando

**Review by AdrianAndersen — APPROVED** [review]
Wow, with the latest commit, this really shines 😘 😉

**Pull request merged**
