### PR TITLE
feat(reporter): copy directly into bl-admin

### PR DESCRIPTION
**Pull request by AdrianAndersen**

### CODE REVIEW

**Comment by AdrianAndersen** [comment]
I have made only a few changes to fix the TypeScript errors and copying over a bit of logic to bl-admins date service

**Comment by AdrianAndersen** [comment]
[Inkluder bl-reporter i bl-admin](https://trello.com/c/7XN3x0pf/1109-inkluder-bl-reporter-i-bl-admin)

**Review by LarsSelbekk — APPROVED** [review]
Going over this line-by-line would be prohibitive, but it seems to work and my attempt at a directory diff doesn't look too bad

**Comment by AdrianAndersen** [comment]
Time to archive bl-reporter 🎉

**Pull request merged**
