### PR TITLE
fix(updateOrderBranch): do not try to update branch for orderItems that are not customerItems

### PR DESCRIPTION
**Pull request by AdrianAndersen**

### CODE REVIEW

**Comment by AdrianAndersen** [comment]
[Fiks feilmelding ved oppdatering av filial for ordre](https://trello.com/c/yFC8APE5/970-fiks-feilmelding-ved-oppdatering-av-filial-for-ordre)

**Comment by LarsSelbekk** [comment]
What is this? I don't get it

**Comment by AdrianAndersen** [comment]
This is related to the functionality for updating the branch an order is related to. When we update the branch for the order, also go through all the customer items related to this order and update their related branch as well. However, there is currently a bug where it just goes through all the _orderItems_, regardless of whether they are actually _customerItems_. This produces an error to the users, since we try to fetch non existing customer items.

To test this, try to update a branch on an order that has not yet been handed out. Eg. "en bestilling mottatt fra bl-web"

**Comment by AdrianAndersen** [comment]
We need this now, so imma merge

**Pull request merged**
